Error: Unable to build url: missing parameter "id" required in route "/case-management/case/:id/:tab" (#6618)
Pass caseId in parameter so that it is always possible to build a route