Fix sandbox deployment (#1016)
Fix the error during deployment:
```
Error: 404 Not Found: The resource server does not exist: 'https://sandbox.sandbox.api.flagright.com/'
```

Regression of fb7038b89ccfb132d7b9a314ac083afa024f65f1