Error: This checker is already assigned to a maker (#6083)
Implement validation instead of showing error that reviewer can not change reviewing role if it's already assigned to somebody