Implements /rules endpoint
Rules are saved under 'flagright' tenant and can  only be modified by
'flagright' tenant. Other tenants can only read the data from 'flagright'
tenant.

GET /rules: returns all rules
e.g
`frun --action get-rules`
```
{
  statusCode: 200,
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*'
  },
  body: [
    {
      id: 'R-1',
      name: 'Awesome rule name',
      description: 'Awesome rule description',
      parametersSchema: {
        type: 'object',
        properties: { threshold: [Object] },
        required: [ 'threshold', [length]: 1 ]
      },
      defaultParameters: { threshold: 3 },
      ruleImplementationFilename: 'code-path'
    },
    {
      id: 'R-2',
      name: 'Awesome rule name',
      description: 'Awesome rule description',
      parametersSchema: {
        type: 'object',
        properties: { threshold: [Object] },
        required: [ 'threshold', [length]: 1 ]
      },
      defaultParameters: { threshold: 3 },
      ruleImplementationFilename: 'code-path-2'
    },
    [length]: 2
  ]
}
```

POST /rules: Create a new rule
e.g
`frun --action create-rule`
Success -
```
{
  statusCode: 200,
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*'
  },
  body: {
    name: 'Awesome rule name',
    description: 'Awesome rule description',
    ruleImplementationFilename: 'code-path-2',
    parametersSchema: {
      type: 'object',
      properties: { threshold: { type: 'number', title: 'Threshold' } },
      required: [ 'threshold', [length]: 1 ]
    },
    defaultParameters: { threshold: 3 },
    id: 'R-2',
    createdAt: 1648039670222,
    updatedAt: 1648039670222
  }
}
```
Invalid json schema -
```
{
  body: {
    error: 'BadRequestError',
    message: 'parametersSchema is not a valid json schema',
    stack: '...'
  },
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*'
  },
  statusCode: 400
}

{
  body: {
    error: 'BadRequestError',
    message: "Invalid defaultParameters: must have required property 'threshold'",
    stack: '...'
  },
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*'
  },
  statusCode: 400
}
```